### ISSUE TITLE
[Bug] On ECONNRESET does not reconnect

### ISSUE THREAD

**Issue by axi92** [emqx/MQTTX#1240]
#### What did I do

Something you have done.
Connect to emqx with username and password SSL/TLS enabled, SSL Secure with CA signed server.
MQTT Version 5.0
Connect Timeout 10
Keep Alive 30
Auto Reconnect true
Reconnect Period 4000ms
Clean Start true

I have a setup with 2 haproxies and keepalived. When I reboot 1 of the LB nodes I get an ECONNRESET and it wont reconnect.
If I connect by hand it works instantly.

#### What happened

Get an error. See the log below.

#### Expected

What is the expected result.
Reconnect. If I connect via the button it is working again.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot
```
[2023-02-21 10:34:52] [INFO] Connect client emqx, MQTT/SSL connection: mqtts://testmqtt.evva.link:443 with Properties: {"sessionExpiryInterval":null,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-02-21 10:34:52] [INFO] emqx connect success, MQTT.js onConnect trigger
[2023-02-21 10:34:52] [INFO] Topic: test/# is resubscribing
[2023-02-21 10:34:52] [INFO] Saved topic: test/#
[2023-02-21 10:34:52] [INFO] Topic: test/# successfully subscribed, Subscription Identifier: null, No Local flag: false, Retain as Published flag: true, Retain Handling: 2
[2023-02-21 10:35:22] [ERROR] emqx connect fail, MQTT.js onError trigger, Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[2023-02-21 10:35:22] [INFO] emqx connect close, MQTT.js onClose trigger
[2023-02-21 10:35:42] [INFO] MQTTX client with ID a7fad073-7d75-49f1-95cc-2a46f4470024 assigned
[2023-02-21 10:35:42] [INFO] Connect client emqx, MQTT/SSL connection: mqtts://testmqtt.evva.link:443 with Properties: {"sessionExpiryInterval":null,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-02-21 10:35:42] [INFO] emqx connect success, MQTT.js onConnect trigger
[2023-02-21 10:35:42] [INFO] Topic: test/# is resubscribing
[2023-02-21 10:35:42] [INFO] Saved topic: test/#
[2023-02-21 10:35:43] [INFO] Topic: test/# successfully subscribed, Subscription Identifier: null, No Local flag: false, Retain as Published flag: true, Retain Handling: 2
[2023-02-21 10:37:42] [ERROR] emqx connect fail, MQTT.js onError trigger, Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[2023-02-21 10:37:42] [INFO] emqx connect close, MQTT.js onClose trigger
[2023-02-21 10:38:01] [INFO] emqx was edited, ID: a7fad073-7d75-49f1-95cc-2a46f4470024
[2023-02-21 10:38:01] [INFO] MQTTX client with ID a7fad073-7d75-49f1-95cc-2a46f4470024 assigned
[2023-02-21 10:38:01] [INFO] Connect client emqx, MQTT/SSL connection: mqtts://testmqtt.evva.link:443 with Properties: {"sessionExpiryInterval":null,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-02-21 10:38:01] [INFO] emqx connect success, MQTT.js onConnect trigger
[2023-02-21 10:38:01] [INFO] Topic: test/# is resubscribing
[2023-02-21 10:38:01] [INFO] Saved topic: test/#
[2023-02-21 10:38:01] [INFO] Topic: test/# successfully subscribed, Subscription Identifier: null, No Local flag: false, Retain as Published flag: true, Retain Handling: 2
[2023-02-21 10:39:01] [INFO] emqx connect close, MQTT.js onClose trigger
[2023-02-21 10:39:05] [INFO] emqx reconnect: 0 times retry
[2023-02-21 10:39:05] [INFO] emqx connect success, MQTT.js onConnect trigger
[2023-02-21 10:39:05] [INFO] Topic: test/# is resubscribing
[2023-02-21 10:39:05] [ERROR] Topic: subscribe granted empty
[2023-02-21 10:39:05] [INFO] Saved topic: test/#
[2023-02-21 10:39:05] [INFO] Topic: test/# successfully subscribed, Subscription Identifier: null, No Local flag: false, Retain as Published flag: true, Retain Handling: 2
[2023-02-21 10:41:35] [ERROR] emqx connect fail, MQTT.js onError trigger, Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[2023-02-21 10:41:35] [INFO] emqx connect close, MQTT.js onClose trigger
[2023-02-21 10:42:32] [INFO] MQTTX client with ID a7fad073-7d75-49f1-95cc-2a46f4470024 assigned
[2023-02-21 10:42:32] [INFO] Connect client emqx, MQTT/SSL connection: mqtts://testmqtt.evva.link:443 with Properties: {"sessionExpiryInterval":null,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-02-21 10:42:32] [INFO] emqx connect success, MQTT.js onConnect trigger
[2023-02-21 10:42:32] [INFO] Topic: test/# is resubscribing
[2023-02-21 10:42:32] [INFO] Saved topic: test/#
[2023-02-21 10:42:32] [INFO] Topic: test/# successfully subscribed, Subscription Identifier: null, No Local flag: false, Retain as Published flag: true, Retain Handling: 2
[2023-02-21 10:44:02] [ERROR] emqx connect fail, MQTT.js onError trigger, Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[2023-02-21 10:44:02] [INFO] emqx connect close, MQTT.js onClose trigger
```
Probably connected to: #929

**Comment by ysfscream** [comment]
@axi92 Sorry for my late reply.

Based on the log information you provided, it appears that you are experiencing an ECONNRESET error when trying to reconnect to the emqx broker. This occurs when the other side of the TCP connection abruptly closes the connection. In your case, it happens when one of the load balancer nodes is rebooted.

"ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is likely due to one or more application protocol errors. You could look at the MQTT Broker or LB services logs to see if it complains about something.

**Comment by axi92** [comment]
Yes you are right I had an http configuration for haproxie that limits the connection to 50s.
And somehow it does not let reconnect. I removed it and now I dont have the disconnect issue anymore. So I dont have to reconnect either =)
