### ISSUE TITLE
[Bug] Linux 上升级到 1.9.2 后程序不可用

### ISSUE THREAD

**Issue by bambuo** [emqx/MQTTX#1279]
#### Environment

```
$ lsb_release -a

No LSB modules are available.
Distributor ID: Deepin
Description:    Deepin 20.9
Release:        20.9
Codename:       apricot
```

MQTTX 1.9.2

#### More detail

```
$ ./MQTTX-1.9.2.AppImage 

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:16536) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/error/DriverPackageNotInstalledError.js:11:28)
    at SqliteDriver.loadDependencies (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteDriver.js:128:19)
    at new SqliteDriver (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:15)
    at DriverFactory.create (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/driver/DriverFactory.js:45:24)
    at new Connection (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/connection/Connection.js:54:59)
    at ConnectionManager.create (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/connection/ConnectionManager.js:57:26)
    at /tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/index.js:219:66
    at step (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /tmp/.mount_MQTTX-uIgcZh/resources/app.asar/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
(Use `mqttx --trace-warnings ...` to show where the warning was created)
(node:16536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by ysfscream** [comment]
There are some issues with MQTTX 1.9.2 on Linux, which might be caused by the SQLite dependency not being properly bundled in the application.
We will fix this issue as soon as possible and update the installation package.
We apologize for any inconvenience this may have caused, and we appreciate your understanding and patience.

**Comment by ysfscream** [comment]
On my ARM64-based Ubuntu machine, it works fine. Is your machine using the amd64 architecture?

![image](https://user-images.githubusercontent.com/21299158/236657749-7eaf0ea2-260d-41e2-ba14-757faa623d65.png)

**Comment by bambuo** [comment]
> 在我基于 ARM64 的 Ubuntu 机器上，它工作正常。您的机器是否使用 amd64 架构？
> 
> ![图像](https://user-images.githubusercontent.com/21299158/236657749-7eaf0ea2-260d-41e2-ba14-757faa623d65.png)

Yes

**Comment by ysfscream** [comment]
Hello, we have fixed the issue, please re-download and try the new version. We apologize for the inconvenience caused.
