### ISSUE TITLE
Host ws:// socket hang up

### ISSUE THREAD

**Issue by uditvishnoi2** [emqx/MQTTX#1335]
#### Describe the problem you Confuse

We are trying to create websocket host , but it it always says socket hang up . we have checked by changing the port still it does not work . The host mqtt:// works fine. 

#### More detail (optional)
![image](https://github.com/emqx/MQTTX/assets/19321734/4480c9ad-169a-496f-a228-da96803ab70b)

[2023-06-28 18:04:26] [ERROR] nicolis_video_sync connect fail, MQTT.js onError trigger, Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-06-28 18:04:26] [INFO] nicolis_video_sync connect close, MQTT.js onClose trigger
[2023-06-28 18:06:47] [INFO] nicolis_video_sync connect close, MQTT.js onClose trigger
[2023-06-28 18:06:52] [INFO] nicolis_video_sync reconnect: 2 times retry
[2023-06-28 18:06:52] [INFO] nicolis_video_sync connect success, MQTT.js onConnect trigger
[2023-06-28 18:07:14] [INFO] MQTTX client with ID bdff397a-59af-40e0-bae1-a5d649bda649 assigned
[2023-06-28 18:07:14] [INFO] Connect client nicolis_video_sync, MQTT/WS connection: ws://broker.emqx.io:1883/mqtt with Properties: {"sessionExpiryInterval":0,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-06-28 18:07:15] [ERROR] nicolis_video_sync connect fail, MQTT.js onError trigger, Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-06-28 18:07:15] [INFO] nicolis_video_sync connect close, MQTT.js onClose trigger
[2023-06-28 18:07:18] [INFO] MQTTX client with ID bdff397a-59af-40e0-bae1-a5d649bda649 assigned
[2023-06-28 18:07:18] [INFO] Connect client nicolis_video_sync, MQTT/WS connection: ws://broker.emqx.io:1883/mqtt with Properties: {"sessionExpiryInterval":0,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-06-28 18:07:18] [ERROR] nicolis_video_sync connect fail, MQTT.js onError trigger, Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-06-28 18:07:18] [INFO] nicolis_video_sync connect close, MQTT.js onClose trigger
[2023-06-28 18:07:30] [INFO] nicolis_video_sync was edited, ID: bdff397a-59af-40e0-bae1-a5d649bda649
[2023-06-28 18:07:31] [INFO] MQTTX client with ID bdff397a-59af-40e0-bae1-a5d649bda649 assigned
[2023-06-28 18:07:31] [INFO] Connect client nicolis_video_sync, MQTT/WS connection: ws://broker.emqx.io:1883/mqtt1 with Properties: {"sessionExpiryInterval":0,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-06-28 18:07:31] [ERROR] nicolis_video_sync connect fail, MQTT.js onError trigger, Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-06-28 18:07:31] [INFO] nicolis_video_sync connect close, MQTT.js onClose trigger
[2023-06-28 18:07:54] [INFO] nicolis_video_sync was edited, ID: bdff397a-59af-40e0-bae1-a5d649bda649
[2023-06-28 18:07:54] [INFO] MQTTX client with ID bdff397a-59af-40e0-bae1-a5d649bda649 assigned
[2023-06-28 18:07:54] [INFO] Connect client nicolis_video_sync, MQTT/WS connection: ws://broker.emqx.io:1883/mqtt with Properties: {"sessionExpiryInterval":0,"receiveMaximum":null,"maximumPacketSize":null,"topicAliasMaximum":null,"requestResponseInformation":null,"requestProblemInformation":null,"authenticationMethod":null}
[2023-06-28 18:07:55] [ERROR] nicolis_video_sync connect fail, MQTT.js onError trigger, Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2023-06-28 18:07:55] [INFO] nicolis_video_sync connect close, MQTT.js onClose trigger
[2023-06-28 18:09:35] [INFO] APP init
[2023-06-28 18:09:37] [INFO] MQTTX client with ID bdff397a-59af-40e0-bae1-a5d649bda649 assigned
[2023-06-28 18:09:37] [INFO] Connect client nicolis_video_sync, MQTT/WS connection: ws://broker.emqx.io:1883/mqtt with Properties:

**Comment by Red-Asuka** [comment]
The port for WebSocket is 8083

<img width="409" alt="image" src="https://github.com/emqx/MQTTX/assets/38158783/fe1dac3b-16c3-470c-83d6-52366356e6e8">

**Comment by uditvishnoi2** [comment]
Yes , right Thank you it is working now. Just a suggestion the port input field should switch to default port when host changes from dropdown.
