### ISSUE TITLE
[ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 8.209.82.158 is not in the cert's list: 

### ISSUE THREAD

**Issue by rribons** [emqx/MQTTX#1456]
[ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 8.209.82.158 is not in the cert's list: 
    at Object.checkServerIdentity (tls.js:297:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

**Comment by ysfscream** [comment]
Hi @rribons, It appears there's an issue with the TLS certificate's altnames, not including the specified IP address. And it seems this issue is a duplicate of https://github.com/emqx/MQTTX/issues/573, and  I recommend referring to [this comment](https://github.com/emqx/MQTTX/issues/573#issuecomment-1774359646) for more insights.

**Comment by ysfscream** [comment]
Hi @rribons, It appears there's an issue with the TLS certificate's altnames, not including the specified IP address. And it seems this issue is a duplicate of https://github.com/emqx/MQTTX/issues/573, and  I recommend referring to [this comment](https://github.com/emqx/MQTTX/issues/573#issuecomment-1774359646) for more insights.
