### ISSUE TITLE
[Bug] Connection fails with: "Error: self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by PawelDefee** [emqx/MQTTX#1506]
#### What did I do

Using MQTTX exactly as before with CA cert, client cert and key.

#### What happened

"Error: self signed certificate in certificate chain"

Broker logs just show:

1701288672: New connection from x.y.z.w:64544 on port 8883.
1701288672: OpenSSL Error[0]: error:0A000126:SSL routines::unexpected eof while reading
1701288672: Client <unknown> disconnected: Protocol error.

#### Expected

Connection should proceed as normal and not get terminated due to usage of self signed certs.

#### Environment

Win10 Pro
MQTTX 1.9.6, also tried some order versions and same thing happens. Tried going back t 1.8.0 but the GUI does not start with that or older versions at all anymore even though the processes are running.

**Comment by PawelDefee** [comment]
MQTTX logs show:

2023-11-29 22:10:52] [INFO] APP init
[2023-11-29 22:11:11] [INFO] MQTTX client with ID e9ac200d-19d0-45e9-ac52-bc4fdd064d41 assigned
[2023-11-29 22:11:11] [INFO] Connect client Demo, MQTT/SSL connection: mqtts://x.y.z.w:8883
[2023-11-29 22:11:11] [ERROR] Demo connect fail, MQTT.js onError trigger, Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

**Comment by PawelDefee** [comment]
Also a strange thing is I cannot find this error text in the MQTTX code to check why this happens.

**Comment by PawelDefee** [comment]
Ok so the error is coming from Node itself. Online sources say that env variable NODE_TLS_REJECT_UNAUTHORIZED has to be set to 0 for this to work.

I did that on the command line (Windows), then started mqttx.exe manually from same shell but same error comes. Node acknowledges that certificate verification is disabled:

[2023-11-29T22:44:45.457] [INFO] default - APP init
[2023-11-29T22:44:47.522] [INFO] default - MQTTX client with ID 2c194093-99ac-4fcd-aad6-86adaa85c7f9 assigned
[2023-11-29T22:44:47.524] [INFO] default - Connect client Demo, MQTT/SSL connection: mqtts://x.y.z.w:8883
(node:5828) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `MQTTX --trace-warnings ...` to show where the warning was created)
[2023-11-29T22:44:47.697] [ERROR] default - Demo connect fail, MQTT.js onError trigger, Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
[2023-11-29T22:44:47.709] [INFO] default - Demo connect close, MQTT.js onClose trigger

**Comment by PawelDefee** [comment]
So, no progress really, not sure if this is the root cause. But see
https://github.com/nodejs/node/blob/8787acb1e62a48cf77c361b571b7aa641e59fb99/lib/internal/options.js#L54C1-L54C1

**Comment by PawelDefee** [comment]
The way I set the environment variable for the user is
[Environment]::SetEnvironmentVariable("NODE_TLS_REJECT_UNAUTHORIZED", "0", "User")

I checked that the variable is set in a separate shell:
gci env:
....
NODE_TLS_REJECT_UNAUTHORIZED   0
...

So this is not effective as a fix but let me know if you have any ideas. One suggestion would be to add 
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;

to MQTTX code.

**Comment by PawelDefee** [comment]
Seems like it might have been an error on my side after all. I recreated the certificates and then MQTTX connection works.

**Comment by PawelDefee** [comment]
The issue can be closed.
