### ISSUE TITLE
packaging       platform=darwin arch=x64 electron=13.6.6 appOutDir=dist_electron/mac   ⨯ cannot resolve https://github.com/electron/electron/releases/download/13.6.6/electron-v13.6.6-darwin-x64.zip

### ISSUE THREAD

**Issue by atorber** [emqx/MQTTX#1708]
when I run `npm run electron:build`

```
• packaging       platform=darwin arch=x64 electron=13.6.6 appOutDir=dist_electron/mac
  ⨯ cannot resolve https://github.com/electron/electron/releases/download/13.6.6/electron-v13.6.6-darwin-x64.zip: status code 404
github.com/develar/app-builder/pkg/download.(Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:237
github.com/develar/app-builder/pkg/download.(Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:1133
ExecError: /Users/luyuchao/Documents/GitHub/MQTTX/node_modules/app-builder-bin/mac/app-builder_arm64 process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/Users/luyuchao/Documents/GitHub/MQTTX/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  exitCode: 1,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
(base) luyuchao@LuChaoMacBook-Pro MQTTX %
(Use `node --trace-warnings ...` to show where the warning was created)
    prebuild-install http 404 https://cdn.npmmirror.com/binaries/sqlite3/v5.1.7/sqlite3-v5.1.7-napi-v36-darwin-x64.tar.gz
    prebuild-install warn install No prebuilt binaries found (target=36 runtime=napi arch=x64 libc= platform=darwin)
    
  • packaging       platform=darwin arch=x64 electron=13.6.6 appOutDir=dist_electron/mac
  ⨯ cannot resolve https://github.com/electron/electron/releases/download/13.6.6/electron-v13.6.6-darwin-x64.zip: status code 404
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:237
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:1133  
ExecError: /Users/luyuchao/Documents/GitHub/MQTTX/node_modules/app-builder-bin/mac/app-builder_arm64 process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/Users/luyuchao/Documents/GitHub/MQTTX/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  exitCode: 1,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
```

**Comment by ysfscream** [comment]
Hi, yes, the URL is returning a 404 error. However, I have tested using the Yarn mirror, and it works https://registry.yarnpkg.com/electron/-/electron-13.6.6.tgz#ebd4754b2b55d54a2e8e9cdc3d0a2bb6b7053827

You might want to use Yarn instead of NPM to run `yarn run electron:build`.

**Comment by atorber** [comment]
I would like to confirm again. Are you running in the environment of the Mac M series?

**Comment by ysfscream** [comment]
> I would like to confirm again. Are you running in the environment of the Mac M series?

Yes, but it has nothing to do with the M chip. It's that the resource content 404, switch to `yarn`, try to reuse `yarn install`, `yarn run electron:build`.

**Comment by ysfscream** [comment]
If there is no update, I will close this issue. Thanks.
