### ISSUE TITLE
TLS problem :  ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by yaobo-lab** [emqx/MQTTX#573]
[2021-05-17 14:17:36] [INFO] Connect close, MQTT.js onClose trigger
[2021-05-17 14:20:53] [INFO] Connect client, MQTT/SSL connection: mqtts://10.0.1.6:8883
[2021-05-17 14:20:53] [INFO] MQTTX client with ID d405d3a0-b170-49b8-a7ea-5297e60c97ab assigned
[2021-05-17 14:20:53] [ERROR] Connect fail, MQTT.js onError trigger, Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 10.0.1.6 is not in the cert's list: 
    at Object.checkServerIdentity (tls.js:261:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1267:27)
    at TLSSocket.emit (events.js:194:13)
    at TLSSocket._finishInit (_tls_wrap.js:734:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:566:12)
[2021-05-17 14:20:53] [INFO] Connect close, MQTT.js onClose trigger

**Comment by ysfscream** [comment]
Hi! Thanks for using MQTT X. I think this is not a bug. It should be that `ALTNAME` is missing from the certificate configuration. Perhaps you can refer to the following link to configure:

https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide

**Comment by yaobo-lab** [comment]
thanks a lot

**Comment by yaobo-lab** [comment]
thanks a lot

**Comment by rribons** [comment]
> Hi! Thanks for using MQTT X. I think this is not a bug. It should be that `ALTNAME` is missing from the certificate configuration. Perhaps you can refer to the following link to configure:
> 
> https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide

sorry,Link display 404

**Comment by Red-Asuka** [comment]
> > Hi! Thanks for using MQTT X. I think this is not a bug. It should be that `ALTNAME` is missing from the certificate configuration. Perhaps you can refer to the following link to configure:
> > https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide
> 
> sorry,Link display 404

https://www.emqx.com/en/blog/emqx-server-ssl-tls-secure-connection-configuration-guide

**Comment by rribons** [comment]
> > > Hi! Thanks for using MQTT X. I think this is not a bug. It should be that `ALTNAME` is missing from the certificate configuration. Perhaps you can refer to the following link to configure:
> > > https://www.emqx.io/blog/emqx-server-ssl-tls-secure-connection-configuration-guide
> > 
> > 
> > sorry,Link display 404
> 
> https://www.emqx.com/en/blog/emqx-server-ssl-tls-secure-connection-configuration-guide

thanks
