### ISSUE TITLE
unable to get issuer certificate

### ISSUE THREAD

**Issue by DongyuanPan** [emqx/MQTTX#987]
use mqttx to connect by slef signed:, and report an error"
[2022-07-14 16:40:53] [ERROR] Connect fail, MQTT.js onError trigger, Error: unable to get issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1257:34)
    at TLSSocket.emit (events.js:194:13)
    at TLSSocket._finishInit (_tls_wrap.js:734:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:566:12)

**Comment by ysfscream** [comment]
Hi, I found some documentation that I hope will help you.

> When ssl certificate problem unable to get local issuer certificate error is caused by a self-signed certificate, the fix is to add the certificate to the trusted certificate store. Open the file ca-bundle. crt located in the directory above, then copy and paste the Git SSL certificate to the end of the file.

ref: https://komodor.com/learn/how-to-fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate-git-error/

**Comment by ysfscream** [comment]
Thanks for the feedback, if there are no more questions, I will close the issue.
